# Generated by Django 3.1.4 on 2021-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookname', models.CharField(default=1, max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('bookname1', models.CharField(default=1, max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ordereditems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=1, max_length=50)),
                ('bookname1', models.CharField(default=1, max_length=50)),
                ('price', models.CharField(default=1, max_length=50)),
                ('quantity', models.CharField(default=1, max_length=50)),
            ],
        ),
    ]
