# Generated by Django 3.1.4 on 2021-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=1, max_length=50)),
                ('bookname1', models.CharField(default=1, max_length=50)),
                ('price', models.CharField(default=1, max_length=50)),
                ('quantity', models.CharField(default=1, max_length=50)),
            ],
        ),
    ]
